import Foundation
import SwiftUI

// A simple class to store and provide Arabic words
class WordStore: ObservableObject {
    static let shared = WordStore()
    
    @Published var words: [ArabicWordItem] = []
    private var isInitializing = false
    
    // Remove initialization from init
    init() {
        // Don't initialize here - we'll do it on demand
    }
    
    func initializeWords() {
        // Skip if already initialized or in progress
        if !words.isEmpty || isInitializing {
            print("WordStore: Words already initialized or initializing, skipping")
            return
        }
        
        // Set flag to prevent concurrent initialization
        isInitializing = true
        
        // Add timing for performance tracking
        let startTime = CFAbsoluteTimeGetCurrent()
        
        // Move this to a background thread
        DispatchQueue.global(qos: .userInitiated).async {
            // Create words array with examples for each letter position
            var newWords: [ArabicWordItem] = [
                // ا (alif)
                ArabicWordItem(id: UUID(), arabic: "أكل", translation: "to eat", transliteration: "akala", category: "verbs", letterPositions: ["ا": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "سأل", translation: "to ask", transliteration: "sa'ala", category: "verbs", letterPositions: ["ا": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "قرأ", translation: "to read", transliteration: "qara'a", category: "verbs", letterPositions: ["ا": "end"]),
                
                // ب (ba)
                ArabicWordItem(id: UUID(), arabic: "بيت", translation: "house", transliteration: "bayt", category: "places", letterPositions: ["ب": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "حبيبي", translation: "my beloved", transliteration: "habibi", category: "expressions", letterPositions: ["ب": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "باب", translation: "door", transliteration: "bab", category: "objects", letterPositions: ["ب": "end"]),
                
                // ت (ta)
                ArabicWordItem(id: UUID(), arabic: "تفاح", translation: "apple", transliteration: "tuffah", category: "food", letterPositions: ["ت": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مكتب", translation: "office", transliteration: "maktab", category: "places", letterPositions: ["ت": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "بنت", translation: "girl", transliteration: "bint", category: "people", letterPositions: ["ت": "end"]),
                
                // ث (tha)
                ArabicWordItem(id: UUID(), arabic: "ثلاثة", translation: "three", transliteration: "thalatha", category: "numbers", letterPositions: ["ث": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مثل", translation: "like/as", transliteration: "mithl", category: "common", letterPositions: ["ث": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "حديث", translation: "modern", transliteration: "hadith", category: "adjectives", letterPositions: ["ث": "end"]),
                
                // ج (jim)
                ArabicWordItem(id: UUID(), arabic: "جميل", translation: "beautiful", transliteration: "jamil", category: "adjectives", letterPositions: ["ج": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مجلس", translation: "council", transliteration: "majlis", category: "places", letterPositions: ["ج": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "ثلج", translation: "snow", transliteration: "thalj", category: "nature", letterPositions: ["ج": "end"]),
                
                // ح (ha)
                ArabicWordItem(id: UUID(), arabic: "حب", translation: "love", transliteration: "hub", category: "emotions", letterPositions: ["ح": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "محمد", translation: "Muhammad", transliteration: "muhammad", category: "names", letterPositions: ["ح": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "مفتاح", translation: "key", transliteration: "miftah", category: "objects", letterPositions: ["ح": "end"]),
                
                // خ (kha)
                ArabicWordItem(id: UUID(), arabic: "خبز", translation: "bread", transliteration: "khubz", category: "food", letterPositions: ["خ": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مخرج", translation: "exit", transliteration: "makhraj", category: "places", letterPositions: ["خ": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "مطبخ", translation: "kitchen", transliteration: "matbakh", category: "places", letterPositions: ["خ": "end"]),
                
                // د (dal)
                ArabicWordItem(id: UUID(), arabic: "درس", translation: "lesson", transliteration: "dars", category: "education", letterPositions: ["د": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مدرسة", translation: "school", transliteration: "madrasa", category: "places", letterPositions: ["د": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "جديد", translation: "new", transliteration: "jadid", category: "adjectives", letterPositions: ["د": "end"]),
                
                // ذ (dhal)
                ArabicWordItem(id: UUID(), arabic: "ذهب", translation: "gold", transliteration: "dhahab", category: "objects", letterPositions: ["ذ": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "إذا", translation: "if", transliteration: "idha", category: "common", letterPositions: ["ذ": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "لذيذ", translation: "delicious", transliteration: "ladhidh", category: "adjectives", letterPositions: ["ذ": "end"]),
                
                // ر (ra)
                ArabicWordItem(id: UUID(), arabic: "رجل", translation: "man", transliteration: "rajul", category: "people", letterPositions: ["ر": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مرحبا", translation: "hello", transliteration: "marhaban", category: "greetings", letterPositions: ["ر": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "كبير", translation: "big", transliteration: "kabir", category: "adjectives", letterPositions: ["ر": "end"]),
                
                // ز (zay)
                ArabicWordItem(id: UUID(), arabic: "زيت", translation: "oil", transliteration: "zayt", category: "food", letterPositions: ["ز": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مزرعة", translation: "farm", transliteration: "mazra'a", category: "places", letterPositions: ["ز": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "خبز", translation: "bread", transliteration: "khubz", category: "food", letterPositions: ["ز": "end"]),
                
                // س (sin)
                ArabicWordItem(id: UUID(), arabic: "سلام", translation: "peace", transliteration: "salam", category: "greetings", letterPositions: ["س": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مدرسة", translation: "school", transliteration: "madrasa", category: "places", letterPositions: ["س": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "درس", translation: "lesson", transliteration: "dars", category: "education", letterPositions: ["س": "end"]),
                
                // ش (shin)
                ArabicWordItem(id: UUID(), arabic: "شمس", translation: "sun", transliteration: "shams", category: "nature", letterPositions: ["ش": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مشروب", translation: "drink", transliteration: "mashrub", category: "food", letterPositions: ["ش": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "مش", translation: "not", transliteration: "mish", category: "common", letterPositions: ["ش": "end"]),
                
                // ص (sad)
                ArabicWordItem(id: UUID(), arabic: "صباح", translation: "morning", transliteration: "sabah", category: "time", letterPositions: ["ص": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "فصل", translation: "season", transliteration: "fasl", category: "time", letterPositions: ["ص": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "رخيص", translation: "cheap", transliteration: "rakhis", category: "adjectives", letterPositions: ["ص": "end"]),
                
                // ض (dad)
                ArabicWordItem(id: UUID(), arabic: "ضوء", translation: "light", transliteration: "daw'", category: "nature", letterPositions: ["ض": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "أخضر", translation: "green", transliteration: "akhdar", category: "colors", letterPositions: ["ض": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "بيض", translation: "eggs", transliteration: "bayd", category: "food", letterPositions: ["ض": "end"]),
                
                // ط (ta)
                ArabicWordItem(id: UUID(), arabic: "طالب", translation: "student", transliteration: "talib", category: "people", letterPositions: ["ط": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مطار", translation: "airport", transliteration: "matar", category: "places", letterPositions: ["ط": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "خط", translation: "line", transliteration: "khat", category: "objects", letterPositions: ["ط": "end"]),
                
                // ظ (za)
                ArabicWordItem(id: UUID(), arabic: "ظهر", translation: "noon", transliteration: "zuhr", category: "time", letterPositions: ["ظ": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "نظام", translation: "system", transliteration: "nizam", category: "common", letterPositions: ["ظ": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "حفظ", translation: "to save", transliteration: "hifz", category: "verbs", letterPositions: ["ظ": "end"]),
                
                // ع (ayn)
                ArabicWordItem(id: UUID(), arabic: "عين", translation: "eye", transliteration: "ayn", category: "body", letterPositions: ["ع": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "معلم", translation: "teacher", transliteration: "mu'allim", category: "people", letterPositions: ["ع": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "سريع", translation: "fast", transliteration: "sari'", category: "adjectives", letterPositions: ["ع": "end"]),
                
                // غ (ghayn)
                ArabicWordItem(id: UUID(), arabic: "غرفة", translation: "room", transliteration: "ghurfa", category: "places", letterPositions: ["غ": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "لغة", translation: "language", transliteration: "lugha", category: "education", letterPositions: ["غ": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "فارغ", translation: "empty", transliteration: "farigh", category: "adjectives", letterPositions: ["غ": "end"]),
                
                // ف (fa)
                ArabicWordItem(id: UUID(), arabic: "فم", translation: "mouth", transliteration: "fam", category: "body", letterPositions: ["ف": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مفتاح", translation: "key", transliteration: "miftah", category: "objects", letterPositions: ["ف": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "صيف", translation: "summer", transliteration: "sayf", category: "time", letterPositions: ["ف": "end"]),
                
                // ق (qaf)
                ArabicWordItem(id: UUID(), arabic: "قلب", translation: "heart", transliteration: "qalb", category: "body", letterPositions: ["ق": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مقهى", translation: "cafe", transliteration: "maqha", category: "places", letterPositions: ["ق": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "سوق", translation: "market", transliteration: "suq", category: "places", letterPositions: ["ق": "end"]),
                
                // ك (kaf)
                ArabicWordItem(id: UUID(), arabic: "كتاب", translation: "book", transliteration: "kitab", category: "objects", letterPositions: ["ك": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "مكتب", translation: "office", transliteration: "maktab", category: "places", letterPositions: ["ك": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "سمك", translation: "fish", transliteration: "samak", category: "food", letterPositions: ["ك": "end"]),
                
                // ل (lam)
                ArabicWordItem(id: UUID(), arabic: "ليل", translation: "night", transliteration: "layl", category: "time", letterPositions: ["ل": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "قلم", translation: "pen", transliteration: "qalam", category: "objects", letterPositions: ["ل": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "جمل", translation: "camel", transliteration: "jamal", category: "animals", letterPositions: ["ل": "end"]),
                
                // م (mim)
                ArabicWordItem(id: UUID(), arabic: "ماء", translation: "water", transliteration: "ma'", category: "nature", letterPositions: ["م": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "شمس", translation: "sun", transliteration: "shams", category: "nature", letterPositions: ["م": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "قلم", translation: "pen", transliteration: "qalam", category: "objects", letterPositions: ["م": "end"]),
                
                // ن (nun)
                ArabicWordItem(id: UUID(), arabic: "نار", translation: "fire", transliteration: "nar", category: "nature", letterPositions: ["ن": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "بنت", translation: "girl", transliteration: "bint", category: "people", letterPositions: ["ن": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "عين", translation: "eye", transliteration: "ayn", category: "body", letterPositions: ["ن": "end"]),
                
                // ه (ha)
                ArabicWordItem(id: UUID(), arabic: "هنا", translation: "here", transliteration: "huna", category: "common", letterPositions: ["ه": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "نهر", translation: "river", transliteration: "nahr", category: "nature", letterPositions: ["ه": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "فواكه", translation: "fruits", transliteration: "fawakeh", category: "food", letterPositions: ["ه": "end"]),
                
                // و (waw)
                ArabicWordItem(id: UUID(), arabic: "ولد", translation: "boy", transliteration: "walad", category: "people", letterPositions: ["و": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "لون", translation: "color", transliteration: "lawn", category: "common", letterPositions: ["و": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "حلو", translation: "sweet", transliteration: "hulw", category: "adjectives", letterPositions: ["و": "end"]),
                
                // ي (ya)
                ArabicWordItem(id: UUID(), arabic: "يد", translation: "hand", transliteration: "yad", category: "body", letterPositions: ["ي": "beginning"]),
                ArabicWordItem(id: UUID(), arabic: "بيت", translation: "house", transliteration: "bayt", category: "places", letterPositions: ["ي": "middle"]),
                ArabicWordItem(id: UUID(), arabic: "كرسي", translation: "chair", transliteration: "kursi", category: "objects", letterPositions: ["ي": "end"])
            ]
            
            // Add more common words
            newWords.append(contentsOf: [
                ArabicWordItem(id: UUID(), arabic: "كيف", translation: "how", transliteration: "kayfa", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "متى", translation: "when", transliteration: "mata", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "أين", translation: "where", transliteration: "ayna", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "لماذا", translation: "why", transliteration: "limadha", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "من", translation: "who", transliteration: "man", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "ماذا", translation: "what", transliteration: "madha", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "كم", translation: "how much/many", transliteration: "kam", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "هل", translation: "do/does", transliteration: "hal", category: "question words"),
                ArabicWordItem(id: UUID(), arabic: "نعم", translation: "yes", transliteration: "na'am", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "لا", translation: "no", transliteration: "la", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أهلا وسهلا", translation: "welcome", transliteration: "ahlan wa sahlan", category: "greetings"),
                ArabicWordItem(id: UUID(), arabic: "إلى اللقاء", translation: "see you later", transliteration: "ila al-liqa'", category: "greetings"),
                ArabicWordItem(id: UUID(), arabic: "تصبح على خير", translation: "good night", transliteration: "tusbih ala khayr", category: "greetings"),
                ArabicWordItem(id: UUID(), arabic: "طيب", translation: "good/okay", transliteration: "tayyib", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "ممتاز", translation: "excellent", transliteration: "mumtaz", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "جيد", translation: "good", transliteration: "jayyid", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "سيء", translation: "bad", transliteration: "sayyi'", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "صغير", translation: "small", transliteration: "saghir", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "كثير", translation: "many/much", transliteration: "kathir", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "قليل", translation: "few/little", transliteration: "qalil", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "طويل", translation: "tall/long", transliteration: "tawil", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "قصير", translation: "short", transliteration: "qasir", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "جديد", translation: "new", transliteration: "jadid", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "قديم", translation: "old", transliteration: "qadim", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "مفتوح", translation: "open", transliteration: "maftuh", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "مغلق", translation: "closed", transliteration: "mughlaq", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "حار", translation: "hot", transliteration: "har", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "بارد", translation: "cold", transliteration: "barid", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "نظيف", translation: "clean", transliteration: "nazif", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "وسخ", translation: "dirty", transliteration: "wasikh", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "سهل", translation: "easy", transliteration: "sahl", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "صعب", translation: "difficult", transliteration: "sa'b", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "مشغول", translation: "busy", transliteration: "mashghul", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "حر", translation: "free", transliteration: "hurr", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "غالي", translation: "expensive", transliteration: "ghali", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "مريض", translation: "sick", transliteration: "marid", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "صحي", translation: "healthy", transliteration: "sihhi", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "سعيد", translation: "happy", transliteration: "sa'id", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "حزين", translation: "sad", transliteration: "hazin", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "غاضب", translation: "angry", transliteration: "ghadib", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "خائف", translation: "afraid", transliteration: "kha'if", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "متعب", translation: "tired", transliteration: "mut'ab", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "جائع", translation: "hungry", transliteration: "ja'i'", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "عطشان", translation: "thirsty", transliteration: "atshan", category: "adjectives"),
                ArabicWordItem(id: UUID(), arabic: "أحمر", translation: "red", transliteration: "ahmar", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "أزرق", translation: "blue", transliteration: "azraq", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "أصفر", translation: "yellow", transliteration: "asfar", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "أسود", translation: "black", transliteration: "aswad", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "أبيض", translation: "white", transliteration: "abyad", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "بني", translation: "brown", transliteration: "bunni", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "رمادي", translation: "gray", transliteration: "ramadi", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "برتقالي", translation: "orange", transliteration: "burtuqali", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "وردي", translation: "pink", transliteration: "wardi", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "بنفسجي", translation: "purple", transliteration: "banafsaji", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "ذهبي", translation: "golden", transliteration: "dhahabi", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "فضي", translation: "silver", transliteration: "fiddi", category: "colors"),
                ArabicWordItem(id: UUID(), arabic: "أب", translation: "father", transliteration: "ab", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "أم", translation: "mother", transliteration: "umm", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "أخ", translation: "brother", transliteration: "akh", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "أخت", translation: "sister", transliteration: "ukht", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "ابن", translation: "son", transliteration: "ibn", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "جد", translation: "grandfather", transliteration: "jadd", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "جدة", translation: "grandmother", transliteration: "jadda", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "عم", translation: "uncle (paternal)", transliteration: "amm", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "عمة", translation: "aunt (paternal)", transliteration: "amma", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "خال", translation: "uncle (maternal)", transliteration: "khal", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "خالة", translation: "aunt (maternal)", transliteration: "khala", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "زوج", translation: "husband", transliteration: "zawj", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "زوجة", translation: "wife", transliteration: "zawja", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "عائلة", translation: "family", transliteration: "a'ila", category: "family"),
                ArabicWordItem(id: UUID(), arabic: "صديق", translation: "friend (m)", transliteration: "sadiq", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "صديقة", translation: "friend (f)", transliteration: "sadiqa", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "جار", translation: "neighbor (m)", transliteration: "jar", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "جارة", translation: "neighbor (f)", transliteration: "jara", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "طفل", translation: "child", transliteration: "tifl", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "امرأة", translation: "woman", transliteration: "imra'a", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "شاب", translation: "young man", transliteration: "shabb", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "شابة", translation: "young woman", transliteration: "shabba", category: "people"),
                ArabicWordItem(id: UUID(), arabic: "طبيب", translation: "doctor", transliteration: "tabib", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "مهندس", translation: "engineer", transliteration: "muhandis", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "معلمة", translation: "teacher (f)", transliteration: "mu'allima", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "طالبة", translation: "student (f)", transliteration: "taliba", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "موظف", translation: "employee", transliteration: "muwazzaf", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "شرطي", translation: "police officer", transliteration: "shurti", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "طيار", translation: "pilot", transliteration: "tayyar", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "محامي", translation: "lawyer", transliteration: "muhami", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "تاجر", translation: "merchant", transliteration: "tajir", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "طباخ", translation: "cook", transliteration: "tabbakh", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "فلاح", translation: "farmer", transliteration: "fallah", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "صحفي", translation: "journalist", transliteration: "sahafi", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "فنان", translation: "artist", transliteration: "fannan", category: "professions"),
                ArabicWordItem(id: UUID(), arabic: "رأس", translation: "head", transliteration: "ra's", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "وجه", translation: "face", transliteration: "wajh", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "شعر", translation: "hair", transliteration: "sha'r", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "أنف", translation: "nose", transliteration: "anf", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "أذن", translation: "ear", transliteration: "udhun", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "ذراع", translation: "arm", transliteration: "dhira'", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "قدم", translation: "foot", transliteration: "qadam", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "ساق", translation: "leg", transliteration: "saq", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "بطن", translation: "stomach", transliteration: "batn", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "كتف", translation: "shoulder", transliteration: "katif", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "أصبع", translation: "finger", transliteration: "isba'", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "شفة", translation: "lip", transliteration: "shafa", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "لسان", translation: "tongue", transliteration: "lisan", category: "body"),
                ArabicWordItem(id: UUID(), arabic: "أكل", translation: "food", transliteration: "akl", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "لحم", translation: "meat", transliteration: "lahm", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "دجاج", translation: "chicken", transliteration: "dajaj", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "جبن", translation: "cheese", transliteration: "jubn", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "حليب", translation: "milk", transliteration: "halib", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "قهوة", translation: "coffee", transliteration: "qahwa", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "شاي", translation: "tea", transliteration: "shay", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "عصير", translation: "juice", transliteration: "asir", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "سكر", translation: "sugar", transliteration: "sukkar", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "ملح", translation: "salt", transliteration: "milh", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "فلفل", translation: "pepper", transliteration: "filfil", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "رز", translation: "rice", transliteration: "ruz", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "خضروات", translation: "vegetables", transliteration: "khudrawat", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "موز", translation: "banana", transliteration: "mawz", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "برتقال", translation: "orange (fruit)", transliteration: "burtuqal", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "عنب", translation: "grapes", transliteration: "inab", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "فراولة", translation: "strawberry", transliteration: "farawla", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "بطيخ", translation: "watermelon", transliteration: "battikh", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "طماطم", translation: "tomato", transliteration: "tamatim", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "خيار", translation: "cucumber", transliteration: "khiyar", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "بصل", translation: "onion", transliteration: "basal", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "ثوم", translation: "garlic", transliteration: "thum", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "بطاطس", translation: "potato", transliteration: "batatis", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "جزر", translation: "carrot", transliteration: "jazar", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "فطور", translation: "breakfast", transliteration: "futur", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "غداء", translation: "lunch", transliteration: "ghada'", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "عشاء", translation: "dinner", transliteration: "asha'", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "حلويات", translation: "sweets", transliteration: "halawiyyat", category: "food"),
                ArabicWordItem(id: UUID(), arabic: "شقة", translation: "apartment", transliteration: "shaqqa", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "حمام", translation: "bathroom", transliteration: "hammam", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "غرفة النوم", translation: "bedroom", transliteration: "ghurfat an-nawm", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "غرفة الجلوس", translation: "living room", transliteration: "ghurfat al-julus", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "نافذة", translation: "window", transliteration: "nafidha", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "سرير", translation: "bed", transliteration: "sarir", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "طاولة", translation: "table", transliteration: "tawila", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "خزانة", translation: "closet", transliteration: "khizana", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "أريكة", translation: "sofa", transliteration: "arika", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "ثلاجة", translation: "refrigerator", transliteration: "thallaja", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "فرن", translation: "oven", transliteration: "furn", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "تلفزيون", translation: "television", transliteration: "tilfizyun", category: "furniture"),
                ArabicWordItem(id: UUID(), arabic: "هاتف", translation: "phone", transliteration: "hatif", category: "technology"),
                ArabicWordItem(id: UUID(), arabic: "حاسوب", translation: "computer", transliteration: "hasub", category: "technology"),
                ArabicWordItem(id: UUID(), arabic: "إنترنت", translation: "internet", transliteration: "intarnit", category: "technology"),
                ArabicWordItem(id: UUID(), arabic: "قرية", translation: "village", transliteration: "qarya", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "شارع", translation: "street", transliteration: "shari'", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "طريق", translation: "road", transliteration: "tariq", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "متجر", translation: "store", transliteration: "matjar", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "مطعم", translation: "restaurant", transliteration: "mat'am", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "فندق", translation: "hotel", transliteration: "funduq", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "مستشفى", translation: "hospital", transliteration: "mustashfa", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "جامعة", translation: "university", transliteration: "jami'a", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "مكتبة", translation: "library", transliteration: "maktaba", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "مسجد", translation: "mosque", transliteration: "masjid", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "كنيسة", translation: "church", transliteration: "kanisa", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "حديقة", translation: "garden/park", transliteration: "hadiqa", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "شاطئ", translation: "beach", transliteration: "shati'", category: "places"),
                ArabicWordItem(id: UUID(), arabic: "جبل", translation: "mountain", transliteration: "jabal", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "بحر", translation: "sea", transliteration: "bahr", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "غابة", translation: "forest", transliteration: "ghaba", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "صحراء", translation: "desert", transliteration: "sahra'", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "سماء", translation: "sky", transliteration: "sama'", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "قمر", translation: "moon", transliteration: "qamar", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "نجم", translation: "star", transliteration: "najm", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "مطر", translation: "rain", transliteration: "matar", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "ثلج", translation: "snow", transliteration: "thalj", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "هواء", translation: "air", transliteration: "hawa'", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "ريح", translation: "wind", transliteration: "rih", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "شجرة", translation: "tree", transliteration: "shajara", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "زهرة", translation: "flower", transliteration: "zahra", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "عشب", translation: "grass", transliteration: "ushb", category: "nature"),
                ArabicWordItem(id: UUID(), arabic: "حيوان", translation: "animal", transliteration: "hayawan", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "كلب", translation: "dog", transliteration: "kalb", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "قط", translation: "cat", transliteration: "qitt", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "حصان", translation: "horse", transliteration: "hisan", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "أسد", translation: "lion", transliteration: "asad", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "فيل", translation: "elephant", transliteration: "fil", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "طائر", translation: "bird", transliteration: "ta'ir", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "سمكة", translation: "fish (single)", transliteration: "samaka", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ثعبان", translation: "snake", transliteration: "thu'ban", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ضفدع", translation: "frog", transliteration: "difda'", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "سلحفاة", translation: "turtle", transliteration: "sulhafa", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "زرافة", translation: "giraffe", transliteration: "zarafa", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "قرد", translation: "monkey", transliteration: "qird", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "دب", translation: "bear", transliteration: "dubb", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ذئب", translation: "wolf", transliteration: "dhi'b", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ثور", translation: "bull", transliteration: "thawr", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "بقرة", translation: "cow", transliteration: "baqara", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "خروف", translation: "sheep", transliteration: "kharuf", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ماعز", translation: "goat", transliteration: "ma'iz", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "دجاجة", translation: "chicken (hen)", transliteration: "dajaja", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "ديك", translation: "rooster", transliteration: "dik", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "بطة", translation: "duck", transliteration: "batta", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "أرنب", translation: "rabbit", transliteration: "arnab", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "فأر", translation: "mouse", transliteration: "fa'r", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "نمر", translation: "tiger", transliteration: "nimr", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "فهد", translation: "cheetah", transliteration: "fahd", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "غزال", translation: "gazelle", transliteration: "ghazal", category: "animals"),
                ArabicWordItem(id: UUID(), arabic: "مساء", translation: "evening", transliteration: "masa'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "يوم", translation: "day", transliteration: "yawm", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "أسبوع", translation: "week", transliteration: "usbu'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "شهر", translation: "month", transliteration: "shahr", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "سنة", translation: "year", transliteration: "sana", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "ساعة", translation: "hour/watch", transliteration: "sa'a", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "دقيقة", translation: "minute", transliteration: "daqiqa", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "ثانية", translation: "second", transliteration: "thaniya", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الآن", translation: "now", transliteration: "al-an", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "غدا", translation: "tomorrow", transliteration: "ghadan", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "أمس", translation: "yesterday", transliteration: "ams", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "اليوم", translation: "today", transliteration: "al-yawm", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الأحد", translation: "Sunday", transliteration: "al-ahad", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الاثنين", translation: "Monday", transliteration: "al-ithnayn", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الثلاثاء", translation: "Tuesday", transliteration: "ath-thulatha'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الأربعاء", translation: "Wednesday", transliteration: "al-arbi'a'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الخميس", translation: "Thursday", transliteration: "al-khamis", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "الجمعة", translation: "Friday", transliteration: "al-jum'a", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "السبت", translation: "Saturday", transliteration: "as-sabt", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "يناير", translation: "January", transliteration: "yanayir", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "فبراير", translation: "February", transliteration: "fibrayir", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "مارس", translation: "March", transliteration: "maris", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "أبريل", translation: "April", transliteration: "abril", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "مايو", translation: "May", transliteration: "mayu", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "يونيو", translation: "June", transliteration: "yunyu", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "يوليو", translation: "July", transliteration: "yulyu", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "أغسطس", translation: "August", transliteration: "aghustus", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "سبتمبر", translation: "September", transliteration: "sibtambar", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "أكتوبر", translation: "October", transliteration: "uktubar", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "نوفمبر", translation: "November", transliteration: "nufambar", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "ديسمبر", translation: "December", transliteration: "disambar", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "ربيع", translation: "spring", transliteration: "rabi'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "خريف", translation: "autumn", transliteration: "kharif", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "شتاء", translation: "winter", transliteration: "shita'", category: "time"),
                ArabicWordItem(id: UUID(), arabic: "سيارة", translation: "car", transliteration: "sayyara", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "حافلة", translation: "bus", transliteration: "hafila", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "قطار", translation: "train", transliteration: "qitar", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "دراجة نارية", translation: "motorcycle", transliteration: "darraja nariya", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "تاكسي", translation: "taxi", transliteration: "taksi", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "مترو", translation: "metro", transliteration: "mitru", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "مجلة", translation: "magazine", transliteration: "majalla", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "جريدة", translation: "newspaper", transliteration: "jarida", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "خريطة", translation: "map", transliteration: "kharita", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "مظلة", translation: "umbrella", transliteration: "mizalla", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "منشفة", translation: "towel", transliteration: "minshafa", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "صابون", translation: "soap", transliteration: "sabun", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "فرشاة أسنان", translation: "toothbrush", transliteration: "furshat asnan", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "معجون أسنان", translation: "toothpaste", transliteration: "ma'jun asnan", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "مشط", translation: "comb", transliteration: "musht", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "مرآة", translation: "mirror", transliteration: "mir'at", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "مقص", translation: "scissors", transliteration: "miqass", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "ملابس", translation: "clothes", transliteration: "malabis", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "قميص", translation: "shirt", transliteration: "qamis", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "بنطلون", translation: "pants", transliteration: "bantalun", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "فستان", translation: "dress", transliteration: "fustan", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "تنورة", translation: "skirt", transliteration: "tannura", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "معطف", translation: "coat", transliteration: "mi'taf", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "جاكيت", translation: "jacket", transliteration: "jakit", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "حذاء", translation: "shoe", transliteration: "hidha'", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "جورب", translation: "sock", transliteration: "jawrab", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "قبعة", translation: "hat", transliteration: "qubba'a", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "حزام", translation: "belt", transliteration: "hizam", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "ربطة عنق", translation: "necktie", transliteration: "rabtat 'unuq", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "قفاز", translation: "glove", transliteration: "quffaz", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "وشاح", translation: "scarf", transliteration: "wishah", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "ساعة يد", translation: "wristwatch", transliteration: "sa'at yad", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "خاتم", translation: "ring", transliteration: "khatim", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "قلادة", translation: "necklace", transliteration: "qilada", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "سوار", translation: "bracelet", transliteration: "siwar", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "أقراط", translation: "earrings", transliteration: "aqrat", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "ذهب", translation: "gold", transliteration: "dhahab", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "فضة", translation: "silver", transliteration: "fidda", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "حديد", translation: "iron", transliteration: "hadid", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "خشب", translation: "wood", transliteration: "khashab", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "زجاج", translation: "glass", transliteration: "zujaj", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "بلاستيك", translation: "plastic", transliteration: "blastik", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "ورق", translation: "paper", transliteration: "waraq", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "قطن", translation: "cotton", transliteration: "qutn", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "صوف", translation: "wool", transliteration: "suf", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "جلد", translation: "leather", transliteration: "jild", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "حجر", translation: "stone", transliteration: "hajar", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "رمل", translation: "sand", transliteration: "raml", category: "materials"),
                ArabicWordItem(id: UUID(), arabic: "أكل", translation: "to eat", transliteration: "akala", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "شرب", translation: "to drink", transliteration: "shariba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "نام", translation: "to sleep", transliteration: "nama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "استيقظ", translation: "to wake up", transliteration: "istayqaza", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ذهب", translation: "to go", transliteration: "dhahaba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "جاء", translation: "to come", transliteration: "ja'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "جلس", translation: "to sit", transliteration: "jalasa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "وقف", translation: "to stand", transliteration: "waqafa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "مشى", translation: "to walk", transliteration: "masha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ركض", translation: "to run", transliteration: "rakada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "قفز", translation: "to jump", transliteration: "qafaza", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "رقص", translation: "to dance", transliteration: "raqasa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "غنى", translation: "to sing", transliteration: "ghanna", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "تكلم", translation: "to speak", transliteration: "takallama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "سمع", translation: "to hear", transliteration: "sami'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "رأى", translation: "to see", transliteration: "ra'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "لمس", translation: "to touch", transliteration: "lamasa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "شم", translation: "to smell", transliteration: "shamma", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ذاق", translation: "to taste", transliteration: "dhaqa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "فتح", translation: "to open", transliteration: "fataha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أغلق", translation: "to close", transliteration: "aghlaqa", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أخذ", translation: "to take", transliteration: "akhadha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أعطى", translation: "to give", transliteration: "a'ta", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "اشترى", translation: "to buy", transliteration: "ishtara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "باع", translation: "to sell", transliteration: "ba'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "دفع", translation: "to pay", transliteration: "dafa'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "سأل", translation: "to ask", transliteration: "sa'ala", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أجاب", translation: "to answer", transliteration: "ajaba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "قرأ", translation: "to read", transliteration: "qara'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "كتب", translation: "to write", transliteration: "kataba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "تعلم", translation: "to learn", transliteration: "ta'allama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "علم", translation: "to teach", transliteration: "'allama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "فهم", translation: "to understand", transliteration: "fahima", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "نسي", translation: "to forget", transliteration: "nasiya", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "تذكر", translation: "to remember", transliteration: "tadhakkara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "بدأ", translation: "to begin", transliteration: "bada'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "انتهى", translation: "to finish", transliteration: "intaha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "عمل", translation: "to work", transliteration: "'amila", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "لعب", translation: "to play", transliteration: "la'iba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ضحك", translation: "to laugh", transliteration: "dahika", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "بكى", translation: "to cry", transliteration: "baka", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ابتسم", translation: "to smile", transliteration: "ibtasama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "عاش", translation: "to live", transliteration: "'asha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "مات", translation: "to die", transliteration: "mata", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ساعد", translation: "to help", transliteration: "sa'ada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أحب", translation: "to love", transliteration: "ahabba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "كره", translation: "to hate", transliteration: "kariha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "فكر", translation: "to think", transliteration: "fakkara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "اعتقد", translation: "to believe", transliteration: "i'taqada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "شعر", translation: "to feel", transliteration: "sha'ara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "أراد", translation: "to want", transliteration: "arada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "احتاج", translation: "to need", transliteration: "ihtaja", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "وجد", translation: "to find", transliteration: "wajada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "فقد", translation: "to lose", transliteration: "faqada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "انتظر", translation: "to wait", transliteration: "intazara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "وصل", translation: "to arrive", transliteration: "wasala", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "غادر", translation: "to leave", transliteration: "ghadara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "سافر", translation: "to travel", transliteration: "safara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "عاد", translation: "to return", transliteration: "'ada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "بقي", translation: "to stay", transliteration: "baqiya", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "سكن", translation: "to live/reside", transliteration: "sakana", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "تزوج", translation: "to marry", transliteration: "tazawwaja", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "ولد", translation: "to be born", transliteration: "wulida", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "نما", translation: "to grow", transliteration: "nama", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "تغير", translation: "to change", transliteration: "taghayyara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "حدث", translation: "to happen", transliteration: "hadatha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "استطاع", translation: "to be able to", transliteration: "istata'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "حاول", translation: "to try", transliteration: "hawala", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "نجح", translation: "to succeed", transliteration: "najaha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "فشل", translation: "to fail", transliteration: "fashila", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "سمح", translation: "to allow", transliteration: "samaha", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "منع", translation: "to prevent", transliteration: "mana'a", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "طلب", translation: "to request", transliteration: "talaba", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "وعد", translation: "to promise", transliteration: "wa'ada", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "شكر", translation: "to thank", transliteration: "shakara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "اعتذر", translation: "to apologize", transliteration: "i'tadhara", category: "verbs"),
                ArabicWordItem(id: UUID(), arabic: "قطار", translation: "train", transliteration: "qitar", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "طائرة", translation: "airplane", transliteration: "ta'ira", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "دراجة", translation: "bicycle", transliteration: "darraja", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "دراجة نارية", translation: "motorcycle", transliteration: "darraja nariya", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "سفينة", translation: "ship", transliteration: "safina", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "قارب", translation: "boat", transliteration: "qarib", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "محطة", translation: "station", transliteration: "mahatta", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "تذكرة", translation: "ticket", transliteration: "tadhkira", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "رحلة", translation: "trip/journey", transliteration: "rihla", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "سفر", translation: "travel", transliteration: "safar", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "جواز سفر", translation: "passport", transliteration: "jawaz safar", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "تأشيرة", translation: "visa", transliteration: "ta'shira", category: "transportation"),
                ArabicWordItem(id: UUID(), arabic: "حقيبة", translation: "bag/suitcase", transliteration: "haqiba", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "مفتاح", translation: "key", transliteration: "miftah", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "ساعة", translation: "watch/clock", transliteration: "sa'a", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "نظارة", translation: "glasses", transliteration: "nazzara", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "محفظة", translation: "wallet", transliteration: "mihfaza", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "قلم", translation: "pen", transliteration: "qalam", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "قلم رصاص", translation: "pencil", transliteration: "qalam rasas", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "ورقة", translation: "paper", transliteration: "waraqa", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "كتاب", translation: "book", transliteration: "kitab", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "دفتر", translation: "notebook", transliteration: "daftar", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "صورة", translation: "picture", transliteration: "sura", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "هدية", translation: "gift", transliteration: "hadiyya", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "لعبة", translation: "toy/game", transliteration: "lu'ba", category: "objects"),
                ArabicWordItem(id: UUID(), arabic: "سترة", translation: "sweater", transliteration: "sutra", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "نظارة شمسية", translation: "sunglasses", transliteration: "nazzara shamsiyya", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "ملابس داخلية", translation: "underwear", transliteration: "malabis dakhiliyya", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "بيجاما", translation: "pajamas", transliteration: "bijama", category: "clothing"),
                ArabicWordItem(id: UUID(), arabic: "ثلاثة", translation: "three", transliteration: "thalatha", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "صفر", translation: "zero", transliteration: "sifr", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "مئة", translation: "hundred", transliteration: "mi'a", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "ألف", translation: "thousand", transliteration: "alf", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "مليون", translation: "million", transliteration: "milyun", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "أول", translation: "first", transliteration: "awwal", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "ثاني", translation: "second", transliteration: "thani", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "ثالث", translation: "third", transliteration: "thalith", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "أخير", translation: "last", transliteration: "akhir", category: "numbers"),
                ArabicWordItem(id: UUID(), arabic: "كل", translation: "all/every", transliteration: "kull", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بعض", translation: "some", transliteration: "ba'd", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "آخر", translation: "other/another", transliteration: "akhar", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "نفس", translation: "same", transliteration: "nafs", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "مختلف", translation: "different", transliteration: "mukhtalif", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "و", translation: "and", transliteration: "wa", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أو", translation: "or", transliteration: "aw", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "لكن", translation: "but", transliteration: "lakin", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "إذا", translation: "if", transliteration: "idha", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "لأن", translation: "because", transliteration: "li'anna", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "حتى", translation: "until/even", transliteration: "hatta", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "منذ", translation: "since", transliteration: "mundhu", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "خلال", translation: "during", transliteration: "khilal", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بعد", translation: "after", transliteration: "ba'da", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "قبل", translation: "before", transliteration: "qabla", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "فوق", translation: "above", transliteration: "fawqa", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "تحت", translation: "under", transliteration: "tahta", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "بين", translation: "between", transliteration: "bayna", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "أمام", translation: "in front of", transliteration: "amama", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "وراء", translation: "behind", transliteration: "wara'a", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "داخل", translation: "inside", transliteration: "dakhil", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "خارج", translation: "outside", transliteration: "kharij", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "قريب", translation: "near", transliteration: "qarib", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "بعيد", translation: "far", transliteration: "ba'id", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "يمين", translation: "right", transliteration: "yamin", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "يسار", translation: "left", transliteration: "yasar", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "شمال", translation: "north", transliteration: "shamal", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "جنوب", translation: "south", transliteration: "janub", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "شرق", translation: "east", transliteration: "sharq", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "غرب", translation: "west", transliteration: "gharb", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "هنا", translation: "here", transliteration: "huna", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "هناك", translation: "there", transliteration: "hunak", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "بجانب", translation: "beside", transliteration: "bi-janib", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "حول", translation: "around", transliteration: "hawla", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "عبر", translation: "across", transliteration: "abra", category: "directions"),
                ArabicWordItem(id: UUID(), arabic: "مع", translation: "with", transliteration: "ma'a", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بدون", translation: "without", transliteration: "bidun", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "عن", translation: "about", transliteration: "an", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "ضد", translation: "against", transliteration: "didda", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "على", translation: "on", transliteration: "ala", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "في", translation: "in", transliteration: "fi", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "إلى", translation: "to", transliteration: "ila", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "من", translation: "from", transliteration: "min", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "عند", translation: "at", transliteration: "inda", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "لـ", translation: "for", transliteration: "li", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بـ", translation: "by/with", transliteration: "bi", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "كـ", translation: "as/like", transliteration: "ka", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "هم", translation: "they", transliteration: "hum", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "أنتم", translation: "you (plural)", transliteration: "antum", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "هذا", translation: "this (m)", transliteration: "hadha", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "هذه", translation: "this (f)", transliteration: "hadhihi", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "ذلك", translation: "that (m)", transliteration: "dhalika", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "تلك", translation: "that (f)", transliteration: "tilka", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "هؤلاء", translation: "these", transliteration: "ha'ula'", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "أولئك", translation: "those", transliteration: "ula'ika", category: "pronouns"),
                ArabicWordItem(id: UUID(), arabic: "ربما", translation: "maybe/perhaps", transliteration: "rubbama", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "فقط", translation: "only/just", transliteration: "faqat", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أيضا", translation: "also/too", transliteration: "aydan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "جدا", translation: "very", transliteration: "jiddan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "تماما", translation: "completely", transliteration: "tamaman", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "حقا", translation: "really/truly", transliteration: "haqqan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "دائما", translation: "always", transliteration: "da'iman", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أبدا", translation: "never", transliteration: "abadan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أحيانا", translation: "sometimes", transliteration: "ahyanan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "غالبا", translation: "often", transliteration: "ghaliban", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "نادرا", translation: "rarely", transliteration: "nadiran", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "سريعا", translation: "quickly", transliteration: "sari'an", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "ببطء", translation: "slowly", transliteration: "bibot'", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بسهولة", translation: "easily", transliteration: "bisuhula", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "بصعوبة", translation: "with difficulty", transliteration: "bisu'uba", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "تقريبا", translation: "approximately", transliteration: "taqriban", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "خاصة", translation: "especially", transliteration: "khassatan", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "فورا", translation: "immediately", transliteration: "fawran", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "أخيرا", translation: "finally", transliteration: "akhiran", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "طبعا", translation: "of course", transliteration: "tab'an", category: "common"),
                ArabicWordItem(id: UUID(), arabic: "من فضلك", translation: "please", transliteration: "min fadlik", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "لو سمحت", translation: "please/excuse me", transliteration: "law samaht", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "شكرا", translation: "thank you", transliteration: "shukran", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "عفوا", translation: "you're welcome", transliteration: "afwan", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "آسف", translation: "sorry (m)", transliteration: "asif", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "آسفة", translation: "sorry (f)", transliteration: "asifa", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "عذرا", translation: "excuse me/pardon", transliteration: "udhran", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "أهلا وسهلا", translation: "welcome", transliteration: "ahlan wa sahlan", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "صباح الخير", translation: "good morning", transliteration: "sabah al-khayr", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "مساء الخير", translation: "good evening", transliteration: "masa' al-khayr", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "تصبح على خير", translation: "good night", transliteration: "tusbih ala khayr", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "مع السلامة", translation: "goodbye (lit: with safety)", transliteration: "ma'a al-salama", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "إلى اللقاء", translation: "goodbye (until we meet again)", transliteration: "ila al-liqa'", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "تفضل", translation: "please go ahead/help yourself (m)", transliteration: "tafaddal", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "تفضلي", translation: "please go ahead/help yourself (f)", transliteration: "tafaddali", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "بالتوفيق", translation: "good luck", transliteration: "bil-tawfiq", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "مبروك", translation: "congratulations", transliteration: "mabruk", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "عيد ميلاد سعيد", translation: "happy birthday", transliteration: "eid milad sa'id", category: "courtesy"),
                ArabicWordItem(id: UUID(), arabic: "كل عام وأنت بخير", translation: "happy holidays/year", transliteration: "kull 'am wa anta bi-khayr", category: "courtesy"),
            ])
            
            // Update on main thread
            DispatchQueue.main.async {
                self.words = newWords
                self.isInitializing = false
                
                let timeElapsed = CFAbsoluteTimeGetCurrent() - startTime
                print("WordStore: Initialized \(self.words.count) Arabic words in \(timeElapsed) seconds")
            }
        }
    }
    
    // Track user progress with words
    func updateWordProgress(wordId: UUID, isCorrect: Bool) {
        // In a real app, you would store this in UserDefaults or a database
        print("Updated progress for word \(wordId): \(isCorrect ? "correct" : "incorrect")")
    }
}

// A simple struct to represent an Arabic word
struct ArabicWordItem: Identifiable {
    var id: UUID
    var arabic: String
    var translation: String
    var transliteration: String
    var category: String
    var letterPositions: [String: String] = [:]
} 